spring.application.name=be

spring.datasource.url=jdbc:mysql://localhost:3306/shoe_store?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=22130309@st.hcmuaf.edu.vn
spring.mail.password=brzb kkhk zuor gmej
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true